Cknieling/update doc
Esri/palladio pull request #190
Opened 2022-10-13 11:48 UTC by chr11115

- Merge all readme files into one
- Extend user manual:
  - Add section to introduce `pldAssign` and `pldGenerate` nodes
  - Update all screenshots
  - Add section for working with multiple assign nodes
  - Add section for working with HDA material
  - Provide RPK needed for the examples in doc/data
- Add new abbreviated Quick Start guide
- Update requirements
- Rename changelog to release notes

Note: currently there is a section where we want the user to check the release notes for the software requirements. This is currently not maintained and should be added to the release notes for the next and all upcoming releases like in puma and serlio

2022-10-26 09:20 UTC, mistafunk requested changes
Overall nice work! Found a bunch of text issues and left-overs

2022-10-26 09:20 UTC, mistafunk commented on README.md
> +1. Open a MSVC 14.2 x64 shell (Visual Studio 2019) and `cd` to the Palladio git repository
```suggestion
1. Open a MSVC 14.27 x64 shell (Visual Studio 2019) and `cd` to the Palladio git repository
```

2022-10-26 09:20 UTC, mistafunk commented on README.md
> +1. Ensure GCC 6.3 is active.
```suggestion
1. Ensure GCC 9.3 is active.
```

2022-10-26 09:20 UTC, mistafunk commented on README.md
> +1. Open a MSVC 14.2 x64 shell (Visual Studio 2019) and `cd` to the Palladio git repository
```suggestion
1. Open a MSVC 14.27 x64 shell (Visual Studio 2019) and `cd` to the Palladio git repository
```

2022-10-26 09:20 UTC, mistafunk commented on README.md
> +1. ensure that the `bin` subdirectory of your Houdini installation is in the `PATH`
this is a leftover from when the tests still depended on Houdini, please remove this line

2022-10-26 09:20 UTC, mistafunk commented on README.md
> +![](doc/img/attribute03.png)
the images in this section are not aligned with the enumeration lists, try to align them

2022-10-31 08:30 UTC, chr11115 commented on README.md
> +1. In CityEngine, download e.g. [Tutorial 9](https://doc.arcgis.com/en/cityengine/latest/tutorials/tutorial-9-advanced-shape-grammar.htm) and export the "Parthenon" CGA rule to a RPK (see [Creating a
added parthenon rpk

2022-11-01 08:51 UTC, mistafunk commented
I've added two doc cleanups, please counter review and merge if happy.

2022-11-01 08:51 UTC, mistafunk approved these changes

2022-11-01 08:53 UTC, chr11115 commented
LGTM, I'll merge

2022-11-01 08:54 UTC, chr11115 commented
LGTM, I'll merge

2022-11-01 08:54 UTC, merged